export const suggestedVideos = [
    {
        title: "Video 1",
        channel: "Channel 1",
        views: "1M views",
        thumbnail: "https://via.placeholder.com/150",
        time: "10 minutes ago",
    },
    {
        title: "Video 2",
        channel: "Channel 2",
        views: "500K views",
        thumbnail: "https://via.placeholder.com/150",
        time: "20 minutes ago",
    },
    {
        title: "Video 1",
        channel: "Channel 1",
        views: "1M views",
        thumbnail: "https://via.placeholder.com/150",
        time: "30 minutes ago",
    },
    {
        title: "Video 2",
        channel: "Channel 2",
        views: "500K views",
        thumbnail: "https://via.placeholder.com/150",
        time: "40 minutes ago",
    },
    {
        title: "Video 1",
        channel: "Channel 1",
        views: "1M views",
        thumbnail: "https://via.placeholder.com/150",
        time: "50 minutes ago",
    },
    {
        title: "Video 2",
        channel: "Channel 2",
        views: "500K views",
        thumbnail: "https://via.placeholder.com/150",
        time: "1 hour ago",
    },
    {
        title: "Video 1",
        channel: "Channel 1",
        views: "1M views",
        thumbnail: "https://via.placeholder.com/150",
        time: "2 hours ago",
    },
    {
        title: "Video 2",
        channel: "Channel 2",
        views: "500K views",
        thumbnail: "https://via.placeholder.com/150",
        time: "3 hours ago",
    },
    {
        title: "Video 1",
        channel: "Channel 1",
        views: "1M views",
        thumbnail: "https://via.placeholder.com/150",
        time: "4 hours ago",
    },
    {
        title: "Video 2",
        channel: "Channel 2",
        views: "500K views",
        thumbnail: "https://via.placeholder.com/150",
        time: "5 hours ago",
    },
    {
        title: "Video 1",
        channel: "Channel 1",
        views: "1M views",
        thumbnail: "https://via.placeholder.com/150",
        time: "6 hours ago",
    },
    {
        title: "Video 2",
        channel: "Channel 2",
        views: "500K views",
        thumbnail: "https://via.placeholder.com/150",
        time: "7 hours ago",
    },
    {
        title: "Video 2",
        channel: "Channel 2",
        views: "500K views",
        thumbnail: "https://via.placeholder.com/150",
        time: "8 hours ago",
    },
];
